# Generated by Django 5.1 on 2024-08-30 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_friendrequests_friendships'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friendships',
            old_name='frnd1',
            new_name='user1',
        ),
        migrations.RenameField(
            model_name='friendships',
            old_name='frnd2',
            new_name='user2',
        ),
        migrations.AlterUniqueTogether(
            name='friendships',
            unique_together={('user1', 'user2')},
        ),
    ]
